# This file generates the GitHub Actions matrix.
---
include:
  - board: assimilator-bt
    shield: imprint_left
    artifact-name: imprint_left

  - board: assimilator-bt
    shield: imprint_right
    artifact-name: imprint_right

  - board: assimilator-bt
    shield: settings_reset
    artifact-name: settings_reset
