CONFIG_ZMK_RGB_UNDERGLOW=y

# Opcional, pero recomendado si quieres recordar el estado de luces
CONFIG_SETTINGS=y

# Bluetooth tuning que ya aparece en configs Cyboard Imprint recientes
CONFIG_BT_PERIPHERAL_PREF_MIN_INT=6
CONFIG_BT_PERIPHERAL_PREF_MAX_INT=6
CONFIG_BT_PERIPHERAL_PREF_LATENCY=0
CONFIG_BT_PERIPHERAL_PREF_TIMEOUT=400
